version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./back/data/db:/var/lib/postgresql/data
    env_file:
      - .env_sample
  web:
    build:
      context: ./
      dockerfile: dockerfile
    image: web
    container_name : web
    volumes:
      - ./back/:/app
    ports:
      - "8000:8000"
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env_sample
    depends_on:
      - db
      