version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env_sample
  web:
    build:
      context: ./
      dockerfile: dockerfile
    image: web
    container_name : web
    volumes:
      - ./back/:/app
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata test_user.json && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env_sample
    depends_on:
      - db
  channels:
    image: redis
    ports:
      - "6379:6379"
