# Generated by Django 5.0.2 on 2024-02-19 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralGameLogs",
            fields=[
                (
                    "game_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "loser",
                    models.ForeignKey(
                        db_column="loser",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_loser",
                        to="users.users",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        db_column="winner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_winner",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "GeneralGameLogs",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="JoinGeneralGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_id",
                    models.ForeignKey(
                        db_column="game_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.generalgamelogs",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "JoinGeneralGame",
            },
        ),
        migrations.CreateModel(
            name="TournamentGameLogs",
            fields=[
                (
                    "tournament_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("round", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_final", models.BooleanField()),
                (
                    "loser",
                    models.ForeignKey(
                        db_column="loser",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_loser",
                        to="users.users",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        db_column="winner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_winner",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "TournamentGameLogs",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="JoinTournamentGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
                (
                    "game_id",
                    models.ForeignKey(
                        db_column="game_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.tournamentgamelogs",
                    ),
                ),
            ],
            options={
                "db_table": "JoinTournamentGame",
            },
        ),
    ]
