# Generated by Django 5.0.2 on 2024-02-19 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intra_id", models.CharField(max_length=20, unique=True)),
                ("nickname", models.CharField(max_length=20, unique=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images"
                    ),
                ),
                ("win_count", models.IntegerField(default=0)),
                ("lose_count", models.IntegerField(default=0)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Online"), ("0", "Offline")], max_length=2
                    ),
                ),
            ],
            options={
                "db_table": "Users",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="FriendRequests",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Accept"), ("0", "Pending")], max_length=2
                    ),
                ),
                (
                    "request_user_id",
                    models.ForeignKey(
                        db_column="request_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_user",
                        to="users.users",
                    ),
                ),
                (
                    "response_user_id",
                    models.ForeignKey(
                        db_column="response_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_user",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "FriendRequests",
                "ordering": ["created_time"],
            },
        ),
    ]
