# Generated by Django 5.0.2 on 2024-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('intra_id', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(upload_to='')),
                ('win_count', models.IntegerField(default=0)),
                ('lose_count', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Online'), ('0', 'Offline')], max_length=2)),
            ],
        ),
    ]
