# Generated by Django 5.0.2 on 2024-02-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequests",
            name="request_user_id",
            field=models.ForeignKey(
                db_column="request_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user",
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequests",
            name="response_user_id",
            field=models.ForeignKey(
                db_column="response_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user",
                to="users.users",
            ),
        ),
    ]
