# Generated by Django 5.0.2 on 2024-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_options_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
