# Generated by Django 5.0.2 on 2024-02-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_users_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="profile_image",
        ),
        migrations.AlterField(
            model_name="users",
            name="intra_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
