# Generated by Django 5.0.2 on 2024-02-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_users_profile_image_alter_users_intra_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="users",
            name="intra_id",
            field=models.CharField(max_length=20),
        ),
    ]
